# Generated by Django 6.0.5 on 2026-06-07 15:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0003_brand'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('barcode', models.CharField(unique=True)),
                ('price', models.FloatField()),
                ('Brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='settings.brand')),
                ('Category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='settings.category')),
            ],
        ),
    ]
